### PR TITLE
Uniform pack of updates

### PR DESCRIPTION
**Pull request by Dr-Yukon**
- new languages - be bg fi he hi id is no pl
- added language explanations
- fixed quotation marks
- made alignment
- corrected italic syntax
- fixed 6 times " FIXME"

### CODE REVIEW

**Comment by Dr-Yukon** [comment]
Ich habe gelernt, servieren Bearbeitungen Bündel. Es war nicht so kompliziert.

Als Referenz. Ich habe das Original kopiert, die korrigierten Dateien in es heruntergeladen, auf https://github.com/splitbrain/dokuwiki-plugin-translation/compare/Dr-Yukon:master und die Vereinigung angefordert

**Comment by splitbrain** [comment]
This is much better to handle for me, thank you. It's not perfect since your individual commits still are nonsensical (badly named, single file edits), but I just need to remember squashing them when I merge. 

PS: can you keep it English in issues please?

**Comment by splitbrain** [comment]
One question: do you speak all those languages? Did you have help by native speakers?

**Comment by splitbrain** [comment]
One more thing, there are quite a few files where you only reformatted whitespace or comments. Adding yourself in them as author is a bit bold, don't you think?

**Comment by Dr-Yukon** [comment]
1. ok. english
2. no. I hope to inspire people to make the fix easier than the initial implementation. a sense of justice is often stronger than laziness
3. sorry, these are automatic things

**Comment by splitbrain** [comment]
I still don't understand. You don't speak those languages but are providing translation updates for be bg fi he hi id is no pl? Are those machine translations?

**Comment by Dr-Yukon** [comment]
yes

**Comment by splitbrain** [comment]
Sorry, I can't accept machine translations. I merged your Belarussian language files.

**Pull request closed without merging**
